#!/usr/bin/env bash
set -euo pipefail

REPO_DIR="$(cd "$(dirname "$0")/.." && pwd)"
# shellcheck source=test/test-helper.sh
source "$REPO_DIR/test/test-helper.sh"

test_root="$(mktemp -d "${TMPDIR:-/tmp}/kalavero-render-test.XXXXXX")"
source_dir="$test_root/source"
opencode_dir="$test_root/opencode"
claude_dir="$test_root/claude"
mkdir -p "$source_dir" "$opencode_dir" "$claude_dir"

cleanup() {
  rm -rf "$test_root"
}
trap cleanup EXIT

cat > "$source_dir/planner.md" <<'AGENT'
---
name: planner
description: Plan work.
tools: Read, Grep, Glob, Bash
---

Plan carefully.
AGENT

cat > "$source_dir/researcher.md" <<'AGENT'
---
name: researcher
description: Research code.
tools: Read, Grep
---

Research carefully.
AGENT

cat > "$opencode_dir/custom.md" <<'AGENT'
---
name: researcher
description: User-managed researcher.
---
AGENT

cat > "$opencode_dir/stale.md" <<'AGENT'
---
# generated by sync.sh from plugins/kalavero/agents - do not edit
name: stale
description: Remove me.
---
AGENT

node "$REPO_DIR/script/render-agents.mjs" opencode "$source_dir" "$opencode_dir" 'openai/gpt-5.6-terra'

assert_file "$opencode_dir/planner.md"
[ ! -e "$opencode_dir/researcher.md" ] || fail 'a user-managed agent name should take precedence'
[ ! -e "$opencode_dir/stale.md" ] || fail 'stale generated agents should be removed'
assert_contains 'model: openai/gpt-5.6-terra' "$opencode_dir/planner.md"
assert_contains '  "*": false' "$opencode_dir/planner.md"
assert_contains '  read: true' "$opencode_dir/planner.md"
assert_contains '  grep: true' "$opencode_dir/planner.md"
assert_contains '  glob: true' "$opencode_dir/planner.md"
assert_contains '  bash: true' "$opencode_dir/planner.md"
assert_not_contains 'tools: Read, Grep, Glob, Bash' "$opencode_dir/planner.md"

node "$REPO_DIR/script/render-agents.mjs" claude "$source_dir" "$claude_dir" 'haiku'

assert_file "$claude_dir/planner.md"
assert_file "$claude_dir/researcher.md"
assert_file "$claude_dir/Explore.md"
assert_file "$claude_dir/Plan.md"
assert_file "$claude_dir/general-purpose.md"
assert_contains 'model: haiku' "$claude_dir/planner.md"
assert_contains 'tools: Read, Grep, Glob, Bash' "$claude_dir/planner.md"

pass 'agent rendering preserves user overrides and emits harness-specific frontmatter'
