#!/usr/bin/env bash
set -euo pipefail

DOTFILES_DIR="$(cd "$(dirname "$0")" && pwd)"
CLAUDE_SUBAGENT_MODEL="haiku"
OPENCODE_SUBAGENT_MODEL="openai/gpt-5.6-terra"
CODEX_SUBAGENT_MODEL="gpt-5.6-terra"

echo "==> Syncing Kalavero Dotfiles"
echo ""

link_if_needed() {
  local source="$DOTFILES_DIR/$1"
  local target="$HOME/$2"

  if [ -L "$target" ]; then
    [ "$(readlink "$target")" = "$source" ] && return 0
    rm "$target"
  elif [ -e "$target" ]; then
    local backup="$target.backup.$(date +%Y%m%d%H%M%S)"
    echo "  Backing up existing ~/$2 -> $(basename "$backup")"
    mv "$target" "$backup"
  fi

  mkdir -p "$(dirname "$target")"
  ln -s "$source" "$target"
}

remove_old_symlink() {
  if [ -L "$HOME/$1" ]; then
    echo "  Removing old symlink: ~/$1"
    rm "$HOME/$1"
  fi
}

backup_if_conflict() {
  [ -L "$HOME/$1" ] && return 0
  [ -e "$HOME/$1" ] || return 0
  local backup="$HOME/$1.backup.$(date +%Y%m%d%H%M%S)"
  echo "  Backing up existing ~/$1 -> $(basename "$backup")"
  mv "$HOME/$1" "$backup"
}

# OpenCode requires agent `tools` frontmatter as a map of tool name to boolean,
# while the shared agents use Claude's comma-separated string. Generate
# OpenCode-compatible copies instead of symlinking the shared directory.
generate_opencode_agents() {
  local source_dir="$DOTFILES_DIR/plugins/kalavero/agents"
  local target_dir="$HOME/.config/opencode/agents"
  local marker="generated by sync.sh from plugins/kalavero/agents - do not edit"
  local model="$OPENCODE_SUBAGENT_MODEL"
  local agent_name
  local file
  local target

  if [ -L "$target_dir" ]; then
    if [ "$(readlink "$target_dir")" = "$source_dir" ]; then
      rm "$target_dir"
    else
      echo "  Skipping OpenCode agents: $target_dir is a user-managed symlink" >&2
      return 0
    fi
  fi
  mkdir -p "$target_dir"

  for file in "$target_dir"/*.md; do
    [ -e "$file" ] || continue
    grep -q "$marker" "$file" && rm "$file"
  done

  for file in "$source_dir"/*.md; do
    agent_name="$(awk '/^name:/ { sub(/^name:[[:space:]]*/, ""); print; exit }' "$file")"
    if grep -RqsE "^[[:space:]]*name:[[:space:]]*['\"]?$agent_name['\"]?[[:space:]]*$" "$target_dir"; then
      continue
    fi
    target="$target_dir/$(basename "$file")"
    [ -e "$target" ] && continue
    awk -v marker="$marker" -v model="$model" '
      /^---$/ {
        fence++
        print
        if (fence == 1) {
          print "# " marker
          print "model: " model
        }
        next
      }
      fence == 1 && /^tools:/ {
        sub(/^tools:[[:space:]]*/, "")
        n = split($0, tool_names, /,[[:space:]]*/)
        print "tools:"
        print "  \"*\": false"
        for (i = 1; i <= n; i++) print "  " tolower(tool_names[i]) ": true"
        next
      }
      { print }
    ' "$file" > "$target"
  done
}

generate_claude_agents() {
  local source_dir="$DOTFILES_DIR/plugins/kalavero/agents"
  local target_dir="$HOME/.claude/agents"
  local marker="generated by sync.sh from plugins/kalavero/agents - do not edit"
  local model="$CLAUDE_SUBAGENT_MODEL"
  local agent_name
  local file
  local target

  if [ -L "$target_dir" ]; then
    if [ "$(readlink "$target_dir")" = "$source_dir" ]; then
      rm "$target_dir"
    else
      echo "  Skipping Claude agents: $target_dir is a user-managed symlink" >&2
      return 0
    fi
  fi
  mkdir -p "$target_dir"

  for file in "$target_dir"/*.md; do
    [ -e "$file" ] || continue
    grep -q "$marker" "$file" && rm "$file"
  done

  for file in "$source_dir"/*.md; do
    agent_name="$(awk '/^name:/ { sub(/^name:[[:space:]]*/, ""); print; exit }' "$file")"
    if grep -RqsE "^[[:space:]]*name:[[:space:]]*['\"]?$agent_name['\"]?[[:space:]]*$" "$target_dir"; then
      continue
    fi
    target="$target_dir/$(basename "$file")"
    [ -e "$target" ] && continue
    awk -v marker="$marker" -v model="$model" '
      /^---$/ {
        fence++
        print
        if (fence == 1) {
          print "# " marker
          print "model: " model
        }
        next
      }
      { print }
    ' "$file" > "$target"
  done

  if [ ! -e "$target_dir/Explore.md" ] && ! grep -RqsE "^[[:space:]]*name:[[:space:]]*['\"]?Explore['\"]?[[:space:]]*$" "$target_dir"; then
    cat >"$target_dir/Explore.md" <<EOF
---
# $marker
name: Explore
description: Fast, read-only agent for searching and understanding codebases.
tools: Read, Grep, Glob, Bash
model: $model
---

Explore the codebase efficiently. Read and search only; do not modify files.
Return concise findings with file references.
EOF
  fi

  if [ ! -e "$target_dir/Plan.md" ] && ! grep -RqsE "^[[:space:]]*name:[[:space:]]*['\"]?Plan['\"]?[[:space:]]*$" "$target_dir"; then
    cat >"$target_dir/Plan.md" <<EOF
---
# $marker
name: Plan
description: Read-only agent for gathering context before planning work.
tools: Read, Grep, Glob, Bash
model: $model
---

Gather the codebase context needed for a plan. Do not modify files.
Return concise findings, constraints, and risks with file references.
EOF
  fi

  if [ ! -e "$target_dir/general-purpose.md" ] && ! grep -RqsE "^[[:space:]]*name:[[:space:]]*['\"]?general-purpose['\"]?[[:space:]]*$" "$target_dir"; then
    cat >"$target_dir/general-purpose.md" <<EOF
---
# $marker
name: general-purpose
description: General-purpose agent for complex research and multi-step tasks.
model: $model
---

Complete the delegated task and return a concise result to the parent agent.
EOF
  fi
}

configure_opencode_subagent_model() {
  local target="$HOME/.config/opencode/plugins/kalavero-subagent-model.ts"
  local marker="Generated by sync.sh"

  mkdir -p "$(dirname "$target")"
  if [ -e "$target" ] || [ -L "$target" ]; then
    if ! grep -q "$marker" "$target"; then
      echo "  Skipping OpenCode subagent defaults: $target is user-managed" >&2
      return 0
    fi
  fi
  cat >"$target" <<EOF
// $marker. Explicit agent model settings take precedence.
export default async function () {
  return {
    config: (config) => {
      config.agent ??= {}

      for (const name of ["general", "explore", "scout"]) {
        config.agent[name] ??= {}
        config.agent[name].model ??= "$OPENCODE_SUBAGENT_MODEL"
      }
    },
  }
}
EOF
}

configure_codex_subagent_model() {
  local target="$HOME/.codex/config.toml"
  local candidate="$target.kalavero.$$"
  local validation_dir

  mkdir -p "$(dirname "$target")"
  node - "$target" "$candidate" "$CODEX_SUBAGENT_MODEL" <<'NODE'
const fs = require("fs")

const [target, candidate, model] = process.argv.slice(2)
let content = fs.existsSync(target) ? fs.readFileSync(target, "utf8") : ""
const marker = "# Managed by kalavero sync.sh"
const managedPattern = /(# Managed by kalavero sync\.sh\n\s*default_subagent_model\s*=\s*)["'][^"']*["']/m

if (managedPattern.test(content)) {
  content = content.replace(managedPattern, `$1"${model}"`)
  fs.writeFileSync(candidate, content)
  process.exit(0)
}

if (/^\s*(?:agents|["']agents["'])\.default_subagent_model\s*=/m.test(content)) process.exit(0)
if (/^\s*(?:agents|["']agents["'])\s*[.=]/m.test(content)) {
  console.error(`  Skipping Codex subagent default: ${target} uses a dotted or inline agents table`)
  process.exit(0)
}
if (/^\s*\[\[?\s*(?:agents|["']agents["'])\s*\./m.test(content)) {
  console.error(`  Skipping Codex subagent default: ${target} declares agent subtables without [agents]`)
  process.exit(0)
}

const lines = content.split("\n")
let agentsStart = -1
let agentsEnd = lines.length

for (let index = 0; index < lines.length; index += 1) {
  if (/^\s*\[\s*(?:agents|["']agents["'])\s*\]\s*(?:#.*)?$/.test(lines[index])) {
    agentsStart = index
    continue
  }

  if (agentsStart >= 0 && /^\s*\[.+\]\s*(?:#.*)?$/.test(lines[index])) {
    agentsEnd = index
    break
  }
}

if (agentsStart >= 0) {
  const hasModel = lines
    .slice(agentsStart + 1, agentsEnd)
    .some((line) => /^\s*(?:default_subagent_model|["']default_subagent_model["'])\s*=/.test(line))

  if (hasModel) process.exit(0)
  lines.splice(agentsStart + 1, 0, marker, `default_subagent_model = "${model}"`)
  content = lines.join("\n")
} else {
  content = `${content.trimEnd()}${content.trim() ? "\n\n" : ""}[agents]\n${marker}\ndefault_subagent_model = "${model}"\n`
}

fs.writeFileSync(candidate, content)
NODE

  [ -e "$candidate" ] || return 0

  if command -v codex &>/dev/null; then
    validation_dir="$(mktemp -d "${TMPDIR:-/tmp}/kalavero-codex.XXXXXX")"
    cp "$candidate" "$validation_dir/config.toml"
    if ! CODEX_HOME="$validation_dir" codex features list &>/dev/null; then
      rm -rf "$validation_dir"
      rm "$candidate"
      echo "  Refusing to write invalid Codex config: $target" >&2
      return 1
    fi
    rm -rf "$validation_dir"
  fi

  cp "$candidate" "$target"
  rm "$candidate"
}

echo "==> Checking for old symlinks..."
remove_old_symlink ".zshrc"
remove_old_symlink ".zshenv"
remove_old_symlink ".aliases"
remove_old_symlink ".tmux.conf"
remove_old_symlink ".gitconfig"
remove_old_symlink ".gitignore"
remove_old_symlink ".zsh"
remove_old_symlink ".vim"
remove_old_symlink ".vimrc"

echo "==> Backing up conflicting configs..."
backup_if_conflict ".config/ghostty"
backup_if_conflict ".config/herdr"

echo "==> Linking shared AI workflow assets..."
link_if_needed "plugins/kalavero/commands" ".claude/commands"
link_if_needed "plugins/kalavero/skills" ".claude/skills"
generate_claude_agents

link_if_needed "plugins/kalavero/commands" ".agents/commands"
link_if_needed "plugins/kalavero/skills" ".agents/skills"
link_if_needed "plugins/kalavero/agents" ".agents/agents"

link_if_needed "plugins/kalavero/commands" ".config/opencode/commands"
link_if_needed "plugins/kalavero/skills" ".config/opencode/skills"
generate_opencode_agents

link_if_needed "plugins/kalavero/commands" ".pi/agent/prompts"
link_if_needed "plugins/kalavero/skills" ".pi/agent/skills"

link_if_needed "home/AGENTS.md" ".claude/CLAUDE.md"
link_if_needed "home/AGENTS.md" ".config/opencode/AGENTS.md"
link_if_needed "home/AGENTS.md" ".codex/AGENTS.md"
link_if_needed "home/AGENTS.md" ".pi/agent/AGENTS.md"
link_if_needed "plugins/kalavero/commands" ".codex/commands"
link_if_needed "plugins/kalavero/skills" ".codex/skills"
link_if_needed "plugins/kalavero/agents" ".codex/agents"

echo "==> Configuring lower-cost subagent models..."
configure_opencode_subagent_model
configure_codex_subagent_model

packages=(home zsh aliases starship git neovim tmux bin ghostty herdr)
echo "==> Stowing packages..."
for pkg in "${packages[@]}"; do
  if [ -d "$DOTFILES_DIR/$pkg" ]; then
    echo "  Stowing $pkg..."
    stow -v -d "$DOTFILES_DIR" -t "$HOME" "$pkg"
  fi
done
