#!/usr/bin/env bash
set -euo pipefail

DOTFILES_DIR="$(cd "$(dirname "$0")" && pwd)"

echo "==> Syncing Kalavero Dotfiles"
echo ""

link_if_needed() {
  local source="$DOTFILES_DIR/$1"
  local target="$HOME/$2"

  if [ -L "$target" ]; then
    [ "$(readlink "$target")" = "$source" ] && return 0
    rm "$target"
  elif [ -e "$target" ]; then
    local backup="$target.backup.$(date +%Y%m%d%H%M%S)"
    echo "  Backing up existing ~/$2 -> $(basename "$backup")"
    mv "$target" "$backup"
  fi

  mkdir -p "$(dirname "$target")"
  ln -s "$source" "$target"
}

remove_old_symlink() {
  if [ -L "$HOME/$1" ]; then
    echo "  Removing old symlink: ~/$1"
    rm "$HOME/$1"
  fi
}

backup_if_conflict() {
  [ -L "$HOME/$1" ] && return 0
  [ -e "$HOME/$1" ] || return 0
  local backup="$HOME/$1.backup.$(date +%Y%m%d%H%M%S)"
  echo "  Backing up existing ~/$1 -> $(basename "$backup")"
  mv "$HOME/$1" "$backup"
}

# OpenCode requires agent `tools` frontmatter as a map of tool name to boolean,
# while the shared agents use Claude's comma-separated string. Generate
# OpenCode-compatible copies instead of symlinking the shared directory.
generate_opencode_agents() {
  local source_dir="$DOTFILES_DIR/plugins/kalavero/agents"
  local target_dir="$HOME/.config/opencode/agents"
  local marker="generated by sync.sh from plugins/kalavero/agents - do not edit"
  local file

  [ -L "$target_dir" ] && rm "$target_dir"
  mkdir -p "$target_dir"

  for file in "$target_dir"/*.md; do
    [ -e "$file" ] || continue
    grep -q "$marker" "$file" && rm "$file"
  done

  for file in "$source_dir"/*.md; do
    awk -v marker="$marker" '
      /^---$/ { fence++; print; if (fence == 1) print "# " marker; next }
      fence == 1 && /^tools:/ {
        sub(/^tools:[[:space:]]*/, "")
        n = split($0, tool_names, /,[[:space:]]*/)
        print "tools:"
        print "  \"*\": false"
        for (i = 1; i <= n; i++) print "  " tolower(tool_names[i]) ": true"
        next
      }
      { print }
    ' "$file" > "$target_dir/$(basename "$file")"
  done
}

echo "==> Checking for old symlinks..."
remove_old_symlink ".zshrc"
remove_old_symlink ".zshenv"
remove_old_symlink ".aliases"
remove_old_symlink ".tmux.conf"
remove_old_symlink ".gitconfig"
remove_old_symlink ".gitignore"
remove_old_symlink ".zsh"
remove_old_symlink ".vim"
remove_old_symlink ".vimrc"

echo "==> Backing up conflicting configs..."
backup_if_conflict ".config/ghostty"
backup_if_conflict ".config/herdr"

echo "==> Linking shared AI workflow assets..."
link_if_needed "plugins/kalavero/commands" ".claude/commands"
link_if_needed "plugins/kalavero/skills" ".claude/skills"
link_if_needed "plugins/kalavero/agents" ".claude/agents"

link_if_needed "plugins/kalavero/commands" ".agents/commands"
link_if_needed "plugins/kalavero/skills" ".agents/skills"
link_if_needed "plugins/kalavero/agents" ".agents/agents"

link_if_needed "plugins/kalavero/commands" ".config/opencode/commands"
link_if_needed "plugins/kalavero/skills" ".config/opencode/skills"
generate_opencode_agents

link_if_needed "plugins/kalavero/commands" ".pi/agent/prompts"
link_if_needed "plugins/kalavero/skills" ".pi/agent/skills"

link_if_needed "home/AGENTS.md" ".claude/CLAUDE.md"
link_if_needed "home/AGENTS.md" ".config/opencode/AGENTS.md"
link_if_needed "home/AGENTS.md" ".codex/AGENTS.md"
link_if_needed "home/AGENTS.md" ".pi/agent/AGENTS.md"
link_if_needed "plugins/kalavero/commands" ".codex/commands"
link_if_needed "plugins/kalavero/skills" ".codex/skills"
link_if_needed "plugins/kalavero/agents" ".codex/agents"

packages=(home zsh aliases starship git neovim tmux bin ghostty herdr)
echo "==> Stowing packages..."
for pkg in "${packages[@]}"; do
  if [ -d "$DOTFILES_DIR/$pkg" ]; then
    echo "  Stowing $pkg..."
    stow -v -d "$DOTFILES_DIR" -t "$HOME" "$pkg"
  fi
done
