onboarding = false
[keys]
prefix = "ctrl+a"

# tmux muscle memory
focus_pane_left = ["ctrl+h", "ctrl+left"]
focus_pane_down = ["ctrl+j", "ctrl+down"]
focus_pane_up = ["ctrl+k", "ctrl+up"]
focus_pane_right = ["ctrl+l", "ctrl+right"]
split_vertical = "prefix+v"
split_horizontal = "prefix+s"
new_tab = "prefix+c"
rename_tab = "prefix+comma"
previous_tab = "prefix+p"
next_tab = "prefix+n"
zoom = "ctrl+z"
resize_mode = "prefix+r"
cycle_pane_previous = "prefix+["
cycle_pane_next = "prefix+]"
last_pane = "prefix+a"
detach = "prefix+q"
