#!/usr/bin/env node

import fs from "node:fs"
import path from "node:path"

const [format, sourceDir, targetDir, model] = process.argv.slice(2)
const marker = "generated by sync.sh from plugins/kalavero/agents - do not edit"

if (!['claude', 'opencode'].includes(format) || !sourceDir || !targetDir || !model) {
  console.error('Usage: render-agents.mjs <claude|opencode> <source-dir> <target-dir> <model>')
  process.exit(2)
}

function agentName(content) {
  const frontmatter = content.match(/^---\r?\n([\s\S]*?)\r?\n---(?:\r?\n|$)/)
  if (!frontmatter) return null

  const name = frontmatter[1].match(/^name:\s*['"]?([^'"\r\n]+?)['"]?\s*$/m)
  return name ? name[1] : null
}

function renderedAgent(content) {
  const lines = content.split('\n')
  let fenceCount = 0
  const output = []

  for (const line of lines) {
    if (line === '---') {
      fenceCount += 1
      output.push(line)
      if (fenceCount === 1) {
        output.push(`# ${marker}`)
        output.push(`model: ${model}`)
      }
      continue
    }

    if (format === 'opencode' && fenceCount === 1 && line.startsWith('tools:')) {
      const tools = line
        .slice('tools:'.length)
        .split(',')
        .map((tool) => tool.trim().toLowerCase())
        .filter(Boolean)

      output.push('tools:')
      output.push('  "*": false')
      for (const tool of tools) output.push(`  ${tool}: true`)
      continue
    }

    output.push(line)
  }

  return output.join('\n')
}

function writeIfAvailable(filename, content, names) {
  const target = path.join(targetDir, filename)
  const name = agentName(content)

  if ((name && names.has(name)) || fs.existsSync(target)) return
  fs.writeFileSync(target, content)
  if (name) names.add(name)
}

fs.mkdirSync(targetDir, { recursive: true })

for (const filename of fs.readdirSync(targetDir)) {
  if (!filename.endsWith('.md')) continue
  const target = path.join(targetDir, filename)
  const content = fs.readFileSync(target, 'utf8')
  if (content.includes(marker)) fs.rmSync(target)
}

const existingNames = new Set()
for (const filename of fs.readdirSync(targetDir)) {
  if (!filename.endsWith('.md')) continue
  const name = agentName(fs.readFileSync(path.join(targetDir, filename), 'utf8'))
  if (name) existingNames.add(name)
}

for (const filename of fs.readdirSync(sourceDir).sort()) {
  if (!filename.endsWith('.md')) continue
  const content = fs.readFileSync(path.join(sourceDir, filename), 'utf8')
  writeIfAvailable(filename, renderedAgent(content), existingNames)
}

if (format === 'claude') {
  const builtins = [
    {
      filename: 'Explore.md',
      name: 'Explore',
      description: 'Fast, read-only agent for searching and understanding codebases.',
      tools: 'Read, Grep, Glob, Bash',
      body: 'Explore the codebase efficiently. Read and search only; do not modify files.\nReturn concise findings with file references.',
    },
    {
      filename: 'Plan.md',
      name: 'Plan',
      description: 'Read-only agent for gathering context before planning work.',
      tools: 'Read, Grep, Glob, Bash',
      body: 'Gather the codebase context needed for a plan. Do not modify files.\nReturn concise findings, constraints, and risks with file references.',
    },
    {
      filename: 'general-purpose.md',
      name: 'general-purpose',
      description: 'General-purpose agent for complex research and multi-step tasks.',
      body: 'Complete the delegated task and return a concise result to the parent agent.',
    },
  ]

  for (const builtin of builtins) {
    const tools = builtin.tools ? `\ntools: ${builtin.tools}` : ''
    const content = `---\n# ${marker}\nname: ${builtin.name}\ndescription: ${builtin.description}${tools}\nmodel: ${model}\n---\n\n${builtin.body}\n`
    writeIfAvailable(builtin.filename, content, existingNames)
  }
}
